# Generated by Django 2.1.8 on 2019-05-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=20)),
                ('product_specs', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Refs',
            fields=[
                ('ref_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Refs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('seller_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('id_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Sellers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Selling',
            fields=[
                ('sale_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Selling',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SellingEdits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_id', models.CharField(blank=True, max_length=15, null=True)),
                ('product_id', models.CharField(blank=True, max_length=15, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Selling_edits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('time_sold', models.TimeField(blank=True, null=True)),
                ('date_sold', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Sold',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('price_payed', models.FloatField(blank=True, null=True)),
                ('time_sold', models.TimeField(blank=True, null=True)),
                ('date_sold', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('wallet_amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Wallet',
                'managed': False,
            },
        ),
    ]
